spring.application.name=familY-service-manager


# Configuración de JPA / Hibernate
# 'update' crea las tablas automáticamente si no existen o las actualiza
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para desarrollo)
spring.jpa.show-sql=true

# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
